### ISSUE TITLE
[Bug] v3.1.2的app端口不能设定127.0.0.1

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#10256]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.1.2
**浏览器版本**
chrome

**Bug 描述**
.env文件的配置如下：
```
## 访问配置
HTTP_PORT=127.0.0.1:82
SSH_PORT=2222
MAGNUS_MYSQL_PORT=127.0.0.1:33060
MAGNUS_MARIADB_PORT=127.0.0.1:33061
```

./jmsctl.sh start 报错如下：
```
ERROR: The Compose file './compose/docker-compose-app.yml' is invalid because:
services.web.ports is invalid: Invalid port "127.0.0.1:82:127.0.0.1:82", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

原因是app.yml的ports设定，映射容器里的port也跟着变量一起改了，请问容量里的nginx端口会根据这个HTTP_PORT变量来启动吗？

预期：希望可以docker启动app的host为127.0.0.1，然后再根据需要做本地代理转发出去。
网关是有多IP环境的，并不希望把端口暴露给所有网段。

```
 web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      HTTP_PORT: ${HTTP_PORT:-80}
      USE_IPV6: ${USE_IPV6:-0}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
```

**Comment by wojiushixiaobai** [comment]
改成如下试试：
```yml
 web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      USE_IPV6: ${USE_IPV6:-0}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    ports:
      - ${HTTP_PORT:-80}:-80
```

**Comment by yuanhaoliang** [comment]
```
  web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      HTTP_PORT: 80
      USE_IPV6: ${USE_IPV6:-0}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/nginx/data/logs:/var/log/nginx
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fs http://localhost:80/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net
```
完整要这样改，下面健康检查那里也有引用变量。 



你改的port那里要改成80，填-80估计也是会报错的。
```
 ports:
      - ${HTTP_PORT:-80}:-80
```
