### ISSUE TITLE
[Question] jumpserver celery组件重启

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#11109]
jumpserver版本: v3.3.0
运行环境: kubernetes 1.27
组件部署后cellery组件会出现重启情况，但未影响使用。使用describe pod查看状态显示143退出状态码。
<img width="1041" alt="image" src="https://github.com/jumpserver/jumpserver/assets/109948570/9b7024b5-a795-4c78-896f-026340596a35">

使用logs -p查看服务重启前的日志，也没有报错信息
<img width="1179" alt="image" src="https://github.com/jumpserver/jumpserver/assets/109948570/80a6f9db-3310-406a-a71e-6e3b69a1b5ce">

这个会是什么原因导致的呢?

**Comment by songchaoqiang** [comment]
重启现象看起来很频繁，部署了才不到两天，已经重启将近20次了
<img width="627" alt="image" src="https://github.com/jumpserver/jumpserver/assets/109948570/b07e91c3-68b4-41d9-9dac-7e8f8239936f">

**Comment by maninhill** [comment]
请升级到最新的版本。

**Comment by songchaoqiang** [comment]
最新的版本没有这个问题是吗?

**Comment by maninhill** [comment]
你自己可以查看下近几个版本的更新日志。

**Comment by BaiJiangJie** [comment]
只有 kubernetes 的部署环境会重启吗？

**Comment by songchaoqiang** [comment]
我只有在kubernetes环境使用，目前看起来我这边是一直在重启。

并且，我的版本在昨天已经升级到了v3.5.0，仍然一直重启[https://github.com/jumpserver/jumpserver/issues/11109#issuecomment-1656507993]。
<img width="658" alt="image" src="https://github.com/jumpserver/jumpserver/assets/109948570/c53c6d6c-2c71-4b89-ad47-36d98d220784">

**Comment by songchaoqiang** [comment]
> 

删掉健康检查会导致出现问题情况但是组件不能自我修复状态么?

**Comment by songchaoqiang** [comment]
我觉得和v2.x一样，加上探测失败次数比较好
```
livenessProbe:
  exec:
    command:
    - /bin/bash
    - /opt/jumpserver/utils/check_celery.sh
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

**Comment by BaiJiangJie** [comment]
嗯，好像确实有问题，v3.6 版本修复一下

**Comment by wojiushixiaobai** [comment]
这是 health check 代码，检测下 /tmp 目录的文件是否有问题。
```
/opt/jumpserver/utils# cat check_celery.sh 
#!/bin/bash

set -e

test -e /tmp/worker_ready_ansible
test -e /tmp/worker_ready_celery
test -e /tmp/worker_heartbeat_ansible && test $(($(date +%s) - $(stat -c %Y /tmp/worker_heartbeat_ansible))) -lt 10
test -e /tmp/worker_heartbeat_celery && test $(($(date +%s) - $(stat -c %Y /tmp/worker_heartbeat_celery))) -lt 10
```

如果是无法生成对于的文件，请延长检测时间。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/installer/blob/dev/compose/docker-compose-task.yml#L20

时间改长一点。

**Comment by songchaoqiang** [comment]
好的，我用的是k8s环境，存货探测改成了这样，再观察一下看看
```
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /opt/jumpserver/utils/check_celery.sh
            failureThreshold: 3
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
```
