### ISSUE TITLE
[Bug] docker 设置 HTTP_PORT 后无法工作

### ISSUE THREAD

**Issue by BluYous** [jumpserver/jumpserver#11329]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**浏览器版本**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Bug 描述**
docker 设置 HTTP_PORT 后无法工作

**Bug 重现步骤(有截图更好)**
1. 修改 https://github.com/jumpserver/Dockerfile/blob/master/config_example.conf 里的 HTTP_PORT 设置，这里设置为 6142
2. 按照说明启动 docker compose
3. 打开 localhost:6142 发现无法访问
4. 发现 https://github.com/jumpserver/Dockerfile/blob/master/web/nginx.conf#L31 貌似被写死成了 80
5. 尝试修改 https://github.com/jumpserver/Dockerfile/blob/master/docker-compose.yml#L166 `${HTTP_PORT:-80}:${HTTP_PORT:-80}` 为 `${HTTP_PORT:-80}:80`
6. 重新 compose down&up，能打开页面，但是很多静态资源无法加载，报错 403.

![JumpServer 开源堡垒机](https://github.com/jumpserver/jumpserver/assets/17316317/d90566b5-fe7c-4c9c-b56a-25b3d64df3b1)

**Comment by wojiushixiaobai** [comment]
你自己build 的话自己改下，官方使用的镜像是 [jumpserver/web](https://github.com/jumpserver/docker-web)

其中 - https://github.com/jumpserver/docker-web/blob/master/init.sh 已经正确处理
```sh
if [ -n "${HTTP_PORT}" ]; then
  if [ ! "${HTTPS_PORT}" ] && [ "${HTTP_PORT}" != "80" ]; then
    sed -i "s@listen 80;@listen ${HTTP_PORT};@g" /etc/nginx/conf.d/default.conf
  fi
  if [ ! "${HTTPS_PORT}" ] && [ "${USE_IPV6}" == "1" ]; then
    sed -i "s@# listen \[::\]:80;@listen \[::\]:${HTTP_PORT};@g" /etc/nginx/conf.d/default.conf
  fi
fi
```

**Comment by BluYous** [comment]
@wojiushixiaobai 不考虑下把 HTTP_PORT 作为环境变量传入么？这个明显不应该重新构建才能支持自定义 PORT 啊。换端口不是一个常见的操作吗。

**Comment by BluYous** [comment]
似乎传入环境变量可行，`${HTTP_PORT:-80}:${HTTP_PORT:-80}` 也回滚了，但是依然无法正确打开页面，静态资源还是报 403。
```
  web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    restart: always
    tty: true
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      HTTP_PORT: $HTTP_PORT
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/nginx/data/logs:/var/log/nginx
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
    networks:
      - net
```
