### ISSUE TITLE
docker-compose怎么部署v3.6.2

### ISSUE THREAD

**Issue by aishang1993** [jumpserver/jumpserver#11488]
**请描述您的问题.**
按照 https://github.com/jumpserver/Dockerfile 部署v3.6.2出现了jms_web启动失败：
```
nginx: [emerg] host not found in upstream "chen" in /etc/nginx/conf.d/default.conf:78
```
能不能提供一个最新版本的docker-compose.yml示例

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
docker-compose.yml 里面缺少组件，你可以手动新增，我们等组件完善后会更新
```
  chen:
    image: jumpserver/chen:${VERSION}
    container_name: jms_chen
    restart: always
    tty: true
    environment:
      - CORE_HOST: http://core:8080
      - BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      - LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -f 127.0.0.1:8082/chen"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  kael:
    image: jumpserver/kael:${VERSION}
    container_name: jms_kael
    restart: always
    tty: true
    environment:
      - CORE_HOST: http://core:8080
      - BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      - LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost:8083/kael/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net
```
