### ISSUE TITLE
[Question] Docker方式安装的，每次down重新拉起之后都会有很多组件离线

### ISSUE THREAD

**Issue by liunancun** [jumpserver/jumpserver#11977]
![image](https://github.com/jumpserver/jumpserver/assets/12378933/330bd5ef-ac70-403d-b096-e4ddfbdb5849)

Docker方式安装的，每次down重新拉起之后都会有很多组件离线，是哪里操作不对吗

执行docker-compose down命令停止
再执行docker-compose up -d命令重新拉起

**Comment by BaiJiangJie** [comment]
使用 jmsctl 工具启动。

**Comment by liunancun** [comment]
docker安装的怎么使用jmsctl工具启动

**Comment by BaiJiangJie** [comment]
所有的都是 docker，你是通过什么方式部署的，在线安装、离线包安装，还是一键安装？

**Comment by liunancun** [comment]
docker-compose.xml

jumpserver:
image: jumpserver/jms_all:v3.4.3
container_name: jumpserver
privileged: true
environment:
- SECRET_KEY=xxx
- BOOTSTRAP_TOKEN=xxx
- LOG_LEVEL=ERROR
- DB_HOST=10.40.2.xx
- DB_PORT=3306
- DB_USER=jumpserver
- DB_PASSWORD=xxx
- DB_NAME=jumpserver
- REDIS_HOST=10.40.2.xx
- REDIS_PORT=6379
- REDIS_PASSWORD=xxx
volumes:
- /home/data/jumpserver/core:/opt/jumpserver/data
- /home/data/jumpserver/koko:/opt/koko/data
- /home/data/jumpserver/lion:/opt/lion/data
ports:
- 80:80
- 2222:2222

启动
docker-compose up -d

@BaiJiangJie

**Comment by BaiJiangJie** [comment]
升级到最新版本试一下？

**Comment by wojiushixiaobai** [comment]
你可以在 `docker-compose.yml` 里面自行加入一个 `hostname: jms_all`

```yaml
  jumpserver:
    image: jumpserver/jms_all:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jms_all
    privileged: true
    restart: always
    hostname: jms_all
    ...
```
