### ISSUE TITLE
docker compose v3.8 使用 all-in-one 模式部署  jumpserver 出现错误

### ISSUE THREAD

**Issue by zfchai** [jumpserver/jumpserver#11983]
**docker compose v3.8 部署 jumpserver all-in-one 模式错误.**

- 执行命令，输出如下信息：

```bash
[root@jumpServer ~]# docker compose -f jumpserver-allinone-compose.yaml up -d
[+] Running 4/4
 ✔ Network root_net       Created                                                                                    0.6s 
 ✘ Container jms_mariadb  Error                                                                                      1.3s 
 ✔ Container jms_redis    Healthy                                                                                    1.2s 
 ✔ Container jms_all      Created                                                                                    1.3s 
dependency failed to start: container jms_mariadb is unhealthy
```

- 文件 `jumpserver-allinone-compose.yaml` 编写如下：

```yaml
version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: jms_mariadb
    restart: always
    command: --log-bin --log-basename=mariadb --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MARIADB_PASSWORD: ${DB_PASSWORD:-My123456}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-My123456}
      MARIADB_DATABASE: ${DB_NAME:-jumpserver}
      TZ: "Asia/Shanghai"
    ports:
      - 3306:3306
    healthcheck:
      test: "mysql -h 127.0.0.1 -u root -p $$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      #test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR:-./jms_data}/mariadb/data:/var/lib/mysql
    networks:
      - net

  redis:
    image: redis:6.2
    container_name: jms_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-Rds123456}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Rds123456}
    ports:
      - 6379:6379
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR:-./jms_data}/redis/data:/data
    networks:
      - net

  jumpserver:
    image: jumpserver/jms_all:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jms_all
    privileged: true
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY:-vYneAbsXUhe4BghEeedNL7nfWLwaTTmhnwQMvjYOIG25Ofzghk}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN:-K1ffDfLSIK8SV2PZj6VaxOiv8KuawlJK}
      DEBUG: ${DEBUG:-FALSE}
      LOG_LEVEL: ${LOG_LEVEL:-ERROR}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-My123456}
      DB_NAME: ${DB_NAME:-jumpserver}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Rds123456}
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT:-33061}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT:-33062}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT:-63790}
    ports:
      - ${HTTP_PORT:-80}:80/tcp
      - ${SSH_PORT:-2222}:2222/tcp
      - ${MAGNUS_MYSQL_PORT:-33061}:33061/tcp
      - ${MAGNUS_MARIADB_PORT:-33062}:33062/tcp
      - ${MAGNUS_REDIS_PORT:-63790}:63790/tcp
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost/api/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR:-./jms_data}/core/data:/opt/jumpserver/core/data
      - ${VOLUME_DIR:-./jms_data}/koko/data:/opt/jumpserver/koko/data
      - ${VOLUME_DIR:-./jms_data}/lion/data:/opt/jumpserver/lion/data
      - ${VOLUME_DIR:-./jms_data}/magnus/data:/opt/jumpserver/magnus/data
      - ${VOLUME_DIR:-./jms_data}/chen/data:/opt/jumpserver/chen/data
      - ${VOLUME_DIR:-./jms_data}/kael/data:/opt/jumpserver/kael/data
      - ${VOLUME_DIR:-./jms_data}/nginx/data:/var/log/nginx
    networks:
      - net

networks:
  net:
```
