### ISSUE TITLE
[Bug]  RDP会话一直提示未能找到会话，多次重新连接后才能成功

### ISSUE THREAD

**Issue by Jayzhang1995** [jumpserver/jumpserver#12326]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
使用helm部署三节点集群
imageTag: v3.9.3
![image](https://github.com/jumpserver/jumpserver/assets/24266745/bb943dcf-19a6-4a83-960a-ed09f46783e1)

Chrome 版本 119.0.6045.159（正式版本） (arm64)
windows 2012 r2 standard

**Bug 描述**
远程windows主机或者使用发布服务器访问web会话时，提示未能找到会话，多次重新连接后可以打开。

1.webui报错
![image](https://github.com/jumpserver/jumpserver/assets/24266745/83994a58-d8cb-43a7-8978-4b56229ab7e4)

2.浏览器建立会话被canceled
![image](https://github.com/jumpserver/jumpserver/assets/24266745/fdb9b129-4073-4bce-b707-eee9179c2b85)
3.lion日志
![image](https://github.com/jumpserver/jumpserver/assets/24266745/0377c47f-8df6-452a-a8aa-23ed27110fb1)

4.ingress-nginx日志
![image](https://github.com/jumpserver/jumpserver/assets/24266745/0d03f113-2dc9-4a76-b81f-7e0fade818b3)

**Bug 重现步骤(有截图更好)**
在web终端打开RDP远程桌面或者web资产

**Comment by BaiJiangJie** [comment]
原因是：多次 API 请求没有走到同一个 jms_lion 容器。
前端 Nginx 配置有问题，负载机制要优化一下。保证，API 建立会话 和 WS 连接同时走同一个 jms_lion 容器。

否则，就会出现上面的报错。

**Comment by Jayzhang1995** [comment]
我前端用的是k8s的ingress-nginx，有相关资料可以参考吗

**Comment by wojiushixiaobai** [comment]
helm 部署的应该无此问题，如果你修改过相应的代码，检查下面的配置：
```yaml
# lion Deployment
kind: Deployment
apiVersion: apps/v1
spec:
  template:
    spec:
      containers:
        env:
          - name: SHARE_ROOM_TYPE
            value: redis
```
以及其他 `REDIS` 认证配置。

`ingress` 基于 `service` 的负载验证是无问题的。
