### ISSUE TITLE
syslog导出配置

### ISSUE THREAD

**Issue by Askas00** [jumpserver/jumpserver#13573]
### 产品版本

v3.10.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu 系统22.04.1-Ubuntu

### 🤔 问题描述

参照文档使用docker-compose启动服务，在.env文件中配置SYSLOG参数无效：
SYSLOG_ENABLE=true
SYSLOG_ADDR=xx.xx.xx.xx:514
咨询一下使用docker-compose方式启动的Jumpserver可以配置syslog吗
参考文档：https://github.com/jumpserver/Dockerfile

### 期望结果

无

### 补充信息

无

**Comment by wojiushixiaobai** [comment]
修改下 docker-compose.yml，在 core 组件的 env 下面添加你的对应变量。
或者等待 v4 发布后使用 v4 版本也可以。

**Comment by Askas00** [comment]
在.env文件中新增了
SYSLOG_ENABLE=true
SYSLOG_ADDR=xx.xx.xx.xx:514
还是没输出日志呢

**Comment by wojiushixiaobai** [comment]
修改 `docker-compose.yml` 在 `environment` 段落加入你的变量
```
services:
  core:
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_core
    restart: always
    command: start web
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
      DOMAINS: ${DOMAINS:-}
      SYSLOG_ENABLE: ${SYSLOG_ENABLE}
      SYSLOG_ADDR: ${SYSLOG_ENABLE}
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  celery:
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_celery
    restart: always
    command: start task
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
      DOMAINS: ${DOMAINS:-}
      SYSLOG_ENABLE: ${SYSLOG_ENABLE}
      SYSLOG_ADDR: ${SYSLOG_ENABLE}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net
```
如果无法理解，请等待 v4.0 版本发布后按照你当前的设置可以直接使用。
