### ISSUE TITLE
[Question] DOMAINS 提示登录失败的问题

### ISSUE THREAD

**Issue by cq134cq** [jumpserver/jumpserver#13591]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

用的是DOCKER

### 🤔 问题描述

配置文件有问题，无法登录，请联系管理员或查看最新文档 如果你是管理员，可以更新配置文件解决，设置配置项 DOMAINS
在DOCKER里找不到CONFIG.TXT这个配置文件，请问这个文件应当在那里找

**Comment by wojiushixiaobai** [comment]
- `/opt/jumpserver/config/config.txt`

**Comment by cq134cq** [comment]
![微信图片_20240704084759](https://github.com/jumpserver/jumpserver/assets/95132993/bef9066b-461f-4b31-8d71-15d91bcf9366)
![微信图片_20240704084751](https://github.com/jumpserver/jumpserver/assets/95132993/9b516a10-989d-41d6-8fc6-419ef06b6695)
请问我都以配置好，可是还是出错？

**Comment by wojiushixiaobai** [comment]
10.0.100.169 是堡垒机的 IP 地址还是你自己单独的 SLB 地址？
直接访问 堡垒机 看看是否有此问题

**Comment by cq134cq** [comment]
10.0.100.169是linux,我在LINUX里装了DCOKER，堡垒机装在DOCKER里
![微信图片_20240704130554](https://github.com/jumpserver/jumpserver/assets/95132993/8d2ee559-91a5-4302-b516-6ad1bcd55f64)

**Comment by cq134cq** [comment]
这个文件是DOCKER里那个容器里读取的？我看了所有的容器里没有映射这个目录
/opt/jumpserver/config/config.txt

**Comment by cq134cq** [comment]
我现在装了4.0,还是同样的问题，我是那里配置不对吗？
![8CC6EA6C-A66D-43a4-A1D2-18CE62FEC3A4](https://github.com/jumpserver/jumpserver/assets/95132993/904bb56c-5621-48bd-8ade-0bc55af73683)
![0F01E625-4496-48dd-9BAE-865D5AE49D3C](https://github.com/jumpserver/jumpserver/assets/95132993/cf5a79ee-9b4b-4d9e-9adc-ab75e6f4cbd4)

**Comment by cq134cq** [comment]
![A73EC3C0-C20A-4ef7-B9C6-102737DEBEC7](https://github.com/jumpserver/jumpserver/assets/95132993/a40d95de-2f3a-4b9a-8390-2ac415bf54cf)

**Comment by wojiushixiaobai** [comment]
直连不应该会出现此问题才是，修改后重启下 jumpserver，也可以尝试重启 docker 和服务器再试试

**Comment by smilence86** [comment]
最新all in one镜像根本没有config.txt这个文件，迷醉

最新镜像

REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
jumpserver/jms_all   latest    1c26c1b8e26b   3 weeks ago     2.24GB


```
jumpserver:
    image: jumpserver/jms_all
    container_name: jumpserver
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
      - 2222:2222
    environment:
      TZ: Asia/Shanghai
      # DOMAINS: jumpserver.example.com
      SECRET_KEY: xxx
      BOOTSTRAP_TOKEN: xxx
      LOG_LEVEL: INFO
      DB_ENGINE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: jumpserver
      DB_PASSWORD: xxx
      DB_NAME: jumpserver
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: xxx
    volumes:
      - /data/jumpserver/core/data:/opt/jumpserver/data
      - /data/jumpserver/jsdata:/opt/data
      - /data/jumpserver/koko:/opt/koko/data
      - /data/jumpserver/lion:/opt/lion/data
      - /data/jumpserver/kael:/opt/kael/data
      - /data/jumpserver/chen:/opt/chen/data
```

启动后进入容器内部，没有这个文件: /opt/jumpserver/config/config.txt

![Image](https://github.com/user-attachments/assets/aed8ab0d-9bd7-4877-950b-cd71d7ad572e)

手动添加这个配置文件也不行，DOMAINS没起作用，登录页面报错

Configuration file has problems and cannot be logged in. Please contact the administrator or view latest docs
If you are administrator, you can update the config resolve it, set
DOMAINS=jumpserver.example.com
