### ISSUE TITLE
[经验分享]  纯手动一站式安装jumpserver新版本分享

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#5854]
最近jumpserver升级到新版本的时候，安装方式变成了一键式，虽然方便了，但是对于我们历史老用户，迁移数据比较困难，所以经过一段时间的琢磨，分享一下自己升级的心路历程，也和各位分享一下。

我们的程序都使用docker部署，安装至 /work/jumpserver  目录下，使用docker-compose.yml 进行配置。

我们一共有200多台机器，大概40多人在使用，全部使用的是单节点方式部署，在一台机器上启动了多个docker容器。

下图是目录结构：

![微信截图_20210326193302](https://user-images.githubusercontent.com/1665397/112627691-e389c080-8e6c-11eb-85eb-e2dc3584dcae.png)

每个目录的作用：

* core_data：包含任务调度、回放文件、静态文件，如果是历史数据迁移，请把回放文件复制到core_data/replay目录下。

* core_log：core 的本地日志文件

* gua_data：guacamole本地目录，如果是迁移历史数据，请将原来的jumpserver.key文件复制到 gua_data/keys/ 目录下。

* koko_data：koko本地目录，如果是迁移历史数据，请将原来的access.key 文件复制到 koko_data/keys 目录下。

* nginx_conf：nginx配置文件目录，只放一个jms.conf 。

* nginx_logs：nginx日志目录。

* redis_data：redis持久化存储目录，内有dump.rdb文件。

第一步：准备工作，创建docker子网（手动指定ip，避免与内网ip段冲突）

`docker network create jms --driver bridge --subnet 172.31.0.0/24`

第二步：.env 文件（环境变量，双花括号的部分需要填写自己的值，每次升级只修改version即可）

```
VERSION=v2.8.2

VOLUME_DIR=/work/jumpserver

TZ=Asia/Shanghai
DEBUG=false

SECRET_KEY={{这里是secret key}}
BOOTSTRAP_TOKEN={{这里是bootstrap_token}}
LOG_LEVEL=INFO
SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=false

DB_ENGINE=mysql
DB_HOST={{数据库地址}}
DB_PORT={{数据库端口}}
DB_USER={{数据库用户名}}
DB_PASSWORD={{数据库密码}}
DB_NAME={{数据库名称}}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD={{redis密码}}

CORE_URL=http://core:8080

KOKO_KEY=data/keys/access.key

GUA_KEY=/config/guacamole/data/keys/
GUA_DRIVE_PATH=/config/guacamole/data/drive/
GUA_RECORD_PATH=/config/guacamole/data/record/
GUA_ENABLE_DRIVE=true
GUA_CLEAR_DRIVE_SESSION=true
GUA_CLEAR_DRIVE_SCHEDULE=24

```

第三步： docker-compose.yml 文件

```yaml
version: "3.1"
services:
  core:
    image: jumpserver/core:${VERSION}
    container_name: jms_core
    restart: always
    networks:
    - jms
    environment:
      SECRET_KEY: ${SECRET_KEY}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      DB_ENGINE: ${DB_ENGINE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: ${TZ}
      DEBUG: ${DEBUG}
    depends_on:
    - redis
    volumes:
    - ${VOLUME_DIR}/core_data:/opt/jumpserver/data
    - ${VOLUME_DIR}/core_logs:/opt/jumpserver/logs
  koko:
    image: jumpserver/koko:${VERSION}
    container_name: jms_koko
    restart: always
    networks:
    - jms
    environment:
      CORE_HOST: ${CORE_URL}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      ACCESS_KEY_FILE: ${KOKO_KEY}
      TZ: ${TZ}
    depends_on:
    - core
    volumes:
    - ${VOLUME_DIR}/koko_data:/opt/koko/data
    ports:
    - 2222:2222
  guacamole:
    image: jumpserver/guacamole:${VERSION}
    container_name: jms_guacamole
    restart: always
    networks:
    - jms
    environment:
      JUMPSERVER_SERVER: ${CORE_URL}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      JUMPSERVER_KEY_DIR: ${GUA_KEY}
      JUMPSERVER_DRIVE_PATH: ${GUA_DRIVE_PATH}
      JUMPSERVER_RECORD_PATH: ${GUA_RECORD_PATH}
      JUMPSERVER_ENABLE_DRIVE: ${GUA_ENABLE_DRIVE}
      JUMPSERVER_CLEAR_DRIVE_SESSION: ${GUA_CLEAR_DRIVE_SESSION}
      JUMPSERVER_CLEAR_DRIVE_SCHEDULE: ${GUA_CLEAR_DRIVE_SCHEDULE}
      TZ: ${TZ}
    depends_on:
    - core
    volumes:
    - ${VOLUME_DIR}/gua_data:/config/guacamole/data
  luna:
    image: jumpserver/luna:${VERSION}
    container_name: jms_luna
    networks:
    - jms
  lina:
    image: jumpserver/lina:${VERSION}
    container_name: jms_lina
    networks:
    - jms
  nginx:
    image: jumpserver/nginx:alpine2
    container_name: jms_nginx
    restart: always
    networks:
    - jms
    volumes:
    - ${VOLUME_DIR}/core_data:/data
    - ${VOLUME_DIR}/nginx_conf:/etc/nginx/conf.d
    - ${VOLUME_DIR}/nginx_logs:/var/log/nginx
    ports:
    - 80:80
  redis:
    image: redis:6-alpine
    container_name: jms_redis
    restart: always
    networks:
    - jms
    volumes:
    - ${VOLUME_DIR}/redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  jms:
    external:
      name: jms

```

第四步：nginx配置文件（放置于nginx_conf目录下，jms.conf ）

```
server {
  listen 80;
  server_tokens off;

  client_max_body_size 5000m;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  location / {
    rewrite ^/(.*)$ /ui/$1 last;
  }

# Luna 配置
  location /luna/ {
    proxy_pass http://luna:80;
  }
# 前端 Lina
  location /ui/ {
    proxy_pass http://lina;
  }

# 挂载在本地的配置
  location /media/replay/ {
    add_header Content-Encoding gzip;
    root /data/;
  }
  location /media/ {
    root /data/;
  }
  location /static/ {
    root /data/;
  }

# Koko 配置
  location /koko/ {
    proxy_pass       http://koko:5000;

    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

# Guacamole 配置
  location /guacamole/ {
    proxy_pass http://guacamole:8080/;

    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }

  # OmniDB 配置
  location /omnidb/ws {
    resolver 127.0.0.11 valid=30s;
    set $upstream http://omnidb:8071;
    proxy_pass       $upstream$request_uri;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location /omnidb/ {
    resolver 127.0.0.11 valid=30s;
    set $upstream http://omnidb:8082;
    proxy_pass       $upstream$request_uri;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
  }

  # Core 配置
  location /ws/ {
    proxy_pass http://core:8070;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location /api/ {
    proxy_pass http://core:8080;
  }
  location /core/ {
    proxy_pass http://core:8080;
  }
}
```

以上就是所有的配置，直接在  /work/jumpserver 目录下使用 docker-compose up -d 命令即可启动全部容器。

![微信截图_20210326193302](https://user-images.githubusercontent.com/1665397/112628077-60b53580-8e6d-11eb-9e3e-8f6c1a08d288.png)
