### ISSUE TITLE
[Question] Kubernetes 中部署Jumpserver重启无法登录终端

### ISSUE THREAD

**Issue by pengbotao** [jumpserver/jumpserver#6543]
**请描述您的问题.**

安装好之后可以正常使用，但若重启则无法通过连接机器，网站是正常的，组件状态不正常（安全设置中的组件注册有开启）。

![WX20210726-112608](https://user-images.githubusercontent.com/20223479/126929125-a0b0a1eb-d364-4105-84dc-f44604e4f2bd.png)

镜像版本：jumpserver/jms_all:v2.11.4

最了一下环境变量配置：
```
  env:
  - name: SECRET_KEY
    value:  
  - name: BOOTSTRAP_TOKEN
    value: 
  - name: DB_HOST
    value: 
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: jumpserver
  - name: DB_PASSWORD
    value: 
  - name: DB_NAME
    value: 
  - name: REDIS_HOST
    value: 
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    value: ""
  volumeMounts:
  - name: jumpserver-pv
    mountPath: /opt/jumpserver/data/media
```

LOGS:
<img width="1419" alt="WX20210726-112756@2x" src="https://user-images.githubusercontent.com/20223479/126929201-757c4209-efdf-4fcc-b664-2b9d6638d8c6.png">

**Comment by wojiushixiaobai** [comment]
```  
volumeMounts:
  - name: core-pv
    mountPath: /opt/jumpserver/data/
  - name: koko-pv
    mountPath: /opt/koko/data/
  - name: lion-pv
    mountPath: /opt/lion/data/
```
