### ISSUE TITLE
[Question] v2.12.2升级至v2.13.0遇到Web无法访问，且docker内jms_lb和jms_celery状态unhealthy

### ISSUE THREAD

**Issue by HolyGu** [jumpserver/jumpserver#6694]
从v1.12.2版本升级的，升级后遇到Web无法访问
![image](https://user-images.githubusercontent.com/28488437/130083420-6be874f5-fb25-489b-8651-387e3b19ff74.png)
status命令查看状态显示docker内jms_lb和jms_celery为unhealthy

docker logs -f jms_lb命令无任何日志输出
docker logs -f jms_celery命令输出如下
![image](https://user-images.githubusercontent.com/28488437/130083556-30063eb7-fea1-456a-a376-124842f9a9e6.png)

**Comment by wushengmin** [comment]
同这个问题

**Comment by wojiushixiaobai** [comment]
```sh
vi /opt/jumpserver/config/nginx/lb_http_server.conf
```
```nginx
# Todo: May be can auto discovery
upstream http_server {
  sticky name=jms_route;
  server web:80;  # 修改此处的 nginx:80 为 web:80
  # server HOST2:80;  # 另外的要写真实IP
}
```

**Comment by HolyGu** [comment]
> ```shell
> vi /opt/jumpserver/config/nginx/lb_http_server.conf
> ```
> 
> ```nginx
> # Todo: May be can auto discovery
> upstream http_server {
>   sticky name=jms_route;
>   server web:80;  # 修改此处的 nginx:80 为 web:80
>   # server HOST2:80;  # 另外的要写真实IP
> }
> ```

在此配置文件中默认就是server web:80;

**Comment by HolyGu** [comment]
尝试全新安装v2.13.0，在配置USE_LB=1  HTTPS_PORT=10443以后，也会出现Web无法访问的情况

**Comment by wojiushixiaobai** [comment]
```sh
vi compose/docker-compose-lb.yml
```
```yaml
version: '2.4'

services:
  lb:
    image: jumpserver/nginx:alpine2
    container_name: jms_lb
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${VOLUME_DIR}/lb/log:/var/log/nginx
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${CONFIG_DIR}/nginx/lb_http_server.conf:/etc/nginx/conf.d/default.conf  # 加入此配置
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: "curl -fskL http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
```
