### ISSUE TITLE
[Question] 推送系统用户慢

### ISSUE THREAD

**Issue by liwenson** [jumpserver/jumpserver#7479]
**请描述您的问题.**
推送 一台服务器的系统用户，过程很慢，需要很久才成功，没有查出是哪里导致的

![Dingtalk_20220111160850](https://user-images.githubusercontent.com/19527818/148904909-810177db-b7ba-4c21-b1ae-b92619bf358e.jpg)

![Dingtalk_20220111161231](https://user-images.githubusercontent.com/19527818/148905003-48c1155b-1ad7-4581-8093-a8b424d74c38.jpg)

![Dingtalk_20220111161317](https://user-images.githubusercontent.com/19527818/148905132-97defb8c-1445-4e0b-a9bf-bb35d7e0bd96.jpg)

**Comment by liwenson** [comment]
在 v2.13.0 版本出现这个现象，升级到v2.17.3 版本这个现象依然存在

**Comment by ibuler** [comment]
是不是 sshd 有 dns lookup 啥的，可以手动 ansible 测试一下

**Comment by liwenson** [comment]
在容器外面执行ansible-playbook 是比较快的
![Dingtalk_20220112165422](https://user-images.githubusercontent.com/19527818/149095338-5082f537-08cd-4232-8824-7635b079519a.jpg)

**Comment by liwenson** [comment]
cat useradd.yaml

- hosts: 10.200.75.129
  tasks:
  - name: "add user"
    user:
      name: "test01"
      password: "abc123456"
      state: present

**Comment by liwenson** [comment]
```
cat useradd.yaml

- hosts: 10.200.75.129
  tasks:
  - name: "add user"
    user:
      name: "test01"
      password: "abc123456"
      state: present

```
