### ISSUE TITLE
[Feature] 支持使用Ansible连接到资产

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#8466]
**请描述您的需求或者改进建议.**
版本：2.23.1
目前使用 ansible 连接资产会**导致会话卡住且服务器不执行命令**。

---
ansible hosts.yaml配置文件：
```
all:
  hosts:
    abc:
      ansible_host: "jumpserver"
      ansible_port: "2222"
      ansible_user: "username@systemuser@hostip"
      ansible_ssh_private_key_file: "ssh key file"
      ansible_ssh_extra_args: ""
```

执行 ansible -i hosts.yaml -vvv -m ping abc 会在以下命令卡住且服务器不执行传入的命令：
```
<jumpserver服务器> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="SSH密钥文件"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="用户名"' -o ConnectTimeout=10 -o 'ControlPath="控制路径"' jumpserver服务器 '/bin/sh -c '"'"'echo '"'"'"'"'"'"'"'"'~用户名'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

经测试，是因为 koko 还不支持通过 ssh 参数传入命令，仅支持stdin传入。
以下命令一样会导致会话卡住且服务器不执行传入的命令：
```
ssh username@systemuser@hostip@jumpserver -p 2222 "echo hello"
```
以下命令能成功执行，但会卡住不结束会话。
```
echo "echo hello" | ssh username@systemuser@hostip@jumpserver -p 2222 
```
