### ISSUE TITLE
[Question] 对k8s的授权，能否精确到命名空间的Pod资源

### ISSUE THREAD

**Issue by ixiaoyi93** [jumpserver/jumpserver#8701]
**请描述您的问题.**
在测试jumpserver 版本 v2.24.0 过程中，只能通过全局的资源限制。我尝试着将clusterrole资源绑定到固定的命名空间，但是似乎并没有生效。想了解一下，是目前功能不支持，还是我操作的方式不正确。如果支持改诉求，能否提供相关的文档呢。

**Comment by XiaoMuYi** [comment]
经过测试，发现jumpserver只能识别到clusterrole级别的权限控制。将role 和 namespace绑定就不行，相关文件如下：
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jumpserver
  namespace: dev
roleRef:
  kind: Role
  name: developer
  namespace: dev
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: developer
  namespace: dev
```
现在就是想确认一下，是否真的如此？
