### ISSUE TITLE
[Question] 测试机器可连接性一直不返回结果

### ISSUE THREAD

**Issue by doublewinter0** [jumpserver/jumpserver#9053]
在测试机器可连接性时，一直不返回结果，如下图所示：
![image](https://user-images.githubusercontent.com/22414051/201561320-c7986621-f925-4bad-a6fc-392b764703cb.png)
查看服务，也没有报错信息。
---
jumpserver 版本：v2.22.2
部署方式：k8s 集群
k8s 版本信息
```yaml
clientVersion:
  buildDate: "2022-07-13T14:30:46Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-13T14:23:26Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
```
宿主机版本：CentOS Linux release 7.6.1810 (Core)，内核：Linux version 3.10.0-957.21.3.el7.x86_64
