### ISSUE TITLE
[Question] 连通性测试 ws 错误

### ISSUE THREAD

**Issue by doublewinter0** [jumpserver/jumpserver#9074]
在测试连通性时，遇到如下问题：
![image](https://user-images.githubusercontent.com/22414051/202122559-b0bd5ec5-7267-453a-bf05-7a1996e09302.png)
查看 celery_ansible.log，发现能通
![image](https://user-images.githubusercontent.com/22414051/202123027-67d9c117-df29-44db-ac6f-0c6b3e396762.png)
然后查看 nginx 日志，发现如下错误：
![image](https://user-images.githubusercontent.com/22414051/202124949-fe967b73-ff64-4816-82b3-0108fe2b1077.png)

宿主机版本：CentOS Linux release 7.6.1810 (Core)，内核：Linux version 5.4.224-1.el7.elrepo.x86_64
k8s 版本：
```yaml
clientVersion:
  buildDate: "2021-06-16T13:00:29Z"
  compiler: gc
  gitCommit: 2cb4598553d0a2ca5f3eb7980c99cd8236cc5011
  gitTreeState: clean
  gitVersion: v1.19.12
  goVersion: go1.15.13
  major: "1"
  minor: "19"
  platform: linux/amd64
serverVersion:
  buildDate: "2021-06-16T12:52:44Z"
  compiler: gc
  gitCommit: 2cb4598553d0a2ca5f3eb7980c99cd8236cc5011
  gitTreeState: clean
  gitVersion: v1.19.12
  goVersion: go1.15.13
  major: "1"
  minor: "19"
  platform: linux/amd64
```
jumpserver 版本：v2.22.2
